name: learn-github-actions # name is optional
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
        # finds an action and retrieves it.
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
        # run a command
      - run: npm install -g bats
      - run: bats -v